version: '3'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: /app/docker_helpers/django_startup.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - "3000:3000"

volumes:
  postgres:
